//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Travels = new HashSet<Travel>();
        }
    
        public System.Guid CountryId { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Travel> Travels { get; set; }
    }
}
