//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public File()
        {
            this.PostFiles = new HashSet<PostFile>();
        }
    
        public System.Guid FileId { get; set; }
        public Nullable<System.Guid> FileTypeId { get; set; }
        public string URL { get; set; }
    
        public virtual FileType FileType { get; set; }
        public virtual ICollection<PostFile> PostFiles { get; set; }
    }
}
