//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMessage
    {
        public System.Guid Id { get; set; }
        public System.Guid SenderId { get; set; }
        public string Message { get; set; }
        public System.DateTime Time { get; set; }
        public System.Guid RoomId { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
