//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public System.Guid LikeId { get; set; }
        public System.Guid UserId { get; set; }
        public System.Guid PostId { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
