//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelMap.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChatMember> ChatMembers { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<File> Files { get; set; }
        public virtual DbSet<FileType> FileTypes { get; set; }
        public virtual DbSet<Follower> Followers { get; set; }
        public virtual DbSet<GroupMessage> GroupMessages { get; set; }
        public virtual DbSet<Like> Likes { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<PostFile> PostFiles { get; set; }
        public virtual DbSet<PostType> PostTypes { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<security_Membership> security_Membership { get; set; }
        public virtual DbSet<security_OAuthMembership> security_OAuthMembership { get; set; }
        public virtual DbSet<security_Roles> security_Roles { get; set; }
        public virtual DbSet<Travel> Travels { get; set; }
        public virtual DbSet<UserProfile> UserProfiles { get; set; }
    }
}
