//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostFile
    {
        public System.Guid PostFileId { get; set; }
        public Nullable<System.Guid> PostId { get; set; }
        public Nullable<System.Guid> FileId { get; set; }
    
        public virtual File File { get; set; }
        public virtual Post Post { get; set; }
    }
}
