//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.ChatMembers = new HashSet<ChatMember>();
            this.GroupMessages = new HashSet<GroupMessage>();
        }
    
        public System.Guid Id { get; set; }
        public string RoomName { get; set; }
        public Nullable<System.Guid> CreatorId { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual ICollection<ChatMember> ChatMembers { get; set; }
        public virtual ICollection<GroupMessage> GroupMessages { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
