
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TravelMap.Models
{

using System;
    using System.Collections.Generic;
    
public partial class security_Roles
{

    public security_Roles()
    {

        this.UserProfiles = new HashSet<UserProfile>();

    }


    public System.Guid RoleId { get; set; }

    public string RoleName { get; set; }



    public virtual ICollection<UserProfile> UserProfiles { get; set; }

}

}
