
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace TravelMap.Models
{

using System;

    public partial class Travel
{

    public System.Guid PostId { get; set; }

    public Nullable<System.Guid> CountryId { get; set; }



    public virtual Country Country { get; set; }

    public virtual Post Post { get; set; }

}

}
