//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelMap.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Followers = new HashSet<Follower>();
            this.Followers1 = new HashSet<Follower>();
            this.Posts = new HashSet<Post>();
            this.Travels = new HashSet<Travel>();
            this.security_Roles = new HashSet<security_Roles>();
        }
    
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string Surname { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Phone { get; set; }
        public byte[] Photo { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Follower> Followers { get; set; }
        public virtual ICollection<Follower> Followers1 { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<Travel> Travels { get; set; }
        public virtual ICollection<security_Roles> security_Roles { get; set; }
    }
}
